namespace Piranha.Jawbone.Sdl3;

public enum SdlEventType : uint
{
    None = 0,
    Quit = 0x100,
    Terminating,
    LowMemory,
    WillEnterBackground,
    DidEnterBackground,
    WillEnterForeground,
    DidEnterForeground,
    LocaleChanged,
    SystemThemeChanged,
    Sdl2DisplayEvent = 0x150,
    DisplayOrientation = 0x151,
    DisplayAdded,
    DisplayRemoved,
    DisplayMoved,
    DisplayContentScaleChanged,
    DisplayHdrStateChanged,
    DisplayFirst = DisplayOrientation,
    DisplayLast = DisplayHdrStateChanged,
    Sdl2WindowEvent = 0x200,
    Sdl2SysWmEvent,
    WindowShown = 0x202,
    WindowHidden,
    WindowExposed,
    WindowMoved,
    WindowResized,
    WindowPixelSizeChanged,
    WindowMinimized,
    WindowMaximized,
    WindowRestored,
    WindowMouseEnter,
    WindowMouseLeave,
    WindowFocusGained,
    WindowFocusLost,
    WindowCloseRequested,
    WindowTakeFocus,
    WindowHitTest,
    WindowIccProfChanged,
    WindowDisplayChanged,
    WindowDisplayScaleChanged,
    WindowOccluded,
    WindowEnterFullscreen,
    WindowLeaveFullscreen,
    WindowDestroyed,
    WindowPenEnter,
    WindowPenLeave,
    WindowFirst = WindowShown,
    WindowLast = WindowPenLeave,
    KeyDown = 0x300,
    KeyUp,
    TextEditing,
    TextInput,
    KeyMapChanged,
    KeyboardAdded,
    KeyboardRemoved,
    MouseMotion = 0x400,
    MouseButtonDown,
    MouseButtonUp,
    MouseWheel,
    MouseAdded,
    MouseRemoved,
    JoystickAxisMotion = 0x600,
    JoystickBallMotion,
    JoystickHatMotion,
    JoystickButtonDown,
    JoystickButtonUp,
    JoystickAdded,
    JoystickRemoved,
    JoystickBatteryUpdated,
    JoystickUpdateComplete,
    GamepadAxisMotion = 0x650,
    GamepadButtonDown,
    GamepadButtonUp,
    GamepadAdded,
    GamepadRemoved,
    GamepadRemapped,
    GamepadTouchpadDown,
    GamepadTouchpadMotion,
    GamepadTouchpadUp,
    GamepadSensorUpdate,
    GamepadUpdateComplete,
    GamepadSteamHandleUpdated,
    FingerDown = 0x700,
    FingerUp,
    FingerMotion,
    Sdl2DollarGesture = 0x800,
    Sdl2DollarRecord,
    Sdl2Multigesture,
    ClipboardUpdate = 0x900,
    DropFile = 0x1000,
    DropText,
    DropBegin,
    DropComplete,
    DropPosition,
    AudioDeviceAdded = 0x1100,
    AudioDeviceRemoved,
    AudioDeviceFormatChanged,
    SensorUpdate = 0x1200,
    PenDown = 0x1300,
    PenUp,
    PenMotion,
    PenButtonDown,
    PenButtonUp,
    CameraDeviceAdded = 0x1400,
    CameraDeviceRemoved,
    CameraDeviceApproved,
    CameraDeviceDenied,
    RenderTargetsReset = 0x2000,
    RenderDeviceReset,
    PollSentinel = 0x7f00,
    UserEvent = 0x8000,
    LastEvent = 0xffff
}
