namespace Piranha.Jawbone.Sdl3;

public enum SdlGpuVertexElementFormat // SDL_GPUVertexElementFormat
{
    Invalid = 0, // SDL_GPU_VERTEXELEMENTFORMAT_INVALID
    Int = 1, // SDL_GPU_VERTEXELEMENTFORMAT_INT
    Int2 = 2, // SDL_GPU_VERTEXELEMENTFORMAT_INT2
    Int3 = 3, // SDL_GPU_VERTEXELEMENTFORMAT_INT3
    Int4 = 4, // SDL_GPU_VERTEXELEMENTFORMAT_INT4
    Uint = 5, // SDL_GPU_VERTEXELEMENTFORMAT_UINT
    Uint2 = 6, // SDL_GPU_VERTEXELEMENTFORMAT_UINT2
    Uint3 = 7, // SDL_GPU_VERTEXELEMENTFORMAT_UINT3
    Uint4 = 8, // SDL_GPU_VERTEXELEMENTFORMAT_UINT4
    Float = 9, // SDL_GPU_VERTEXELEMENTFORMAT_FLOAT
    Float2 = 10, // SDL_GPU_VERTEXELEMENTFORMAT_FLOAT2
    Float3 = 11, // SDL_GPU_VERTEXELEMENTFORMAT_FLOAT3
    Float4 = 12, // SDL_GPU_VERTEXELEMENTFORMAT_FLOAT4
    Byte2 = 13, // SDL_GPU_VERTEXELEMENTFORMAT_BYTE2
    Byte4 = 14, // SDL_GPU_VERTEXELEMENTFORMAT_BYTE4
    Ubyte2 = 15, // SDL_GPU_VERTEXELEMENTFORMAT_UBYTE2
    Ubyte4 = 16, // SDL_GPU_VERTEXELEMENTFORMAT_UBYTE4
    Byte2Norm = 17, // SDL_GPU_VERTEXELEMENTFORMAT_BYTE2_NORM
    Byte4Norm = 18, // SDL_GPU_VERTEXELEMENTFORMAT_BYTE4_NORM
    Ubyte2Norm = 19, // SDL_GPU_VERTEXELEMENTFORMAT_UBYTE2_NORM
    Ubyte4Norm = 20, // SDL_GPU_VERTEXELEMENTFORMAT_UBYTE4_NORM
    Short2 = 21, // SDL_GPU_VERTEXELEMENTFORMAT_SHORT2
    Short4 = 22, // SDL_GPU_VERTEXELEMENTFORMAT_SHORT4
    Ushort2 = 23, // SDL_GPU_VERTEXELEMENTFORMAT_USHORT2
    Ushort4 = 24, // SDL_GPU_VERTEXELEMENTFORMAT_USHORT4
    Short2Norm = 25, // SDL_GPU_VERTEXELEMENTFORMAT_SHORT2_NORM
    Short4Norm = 26, // SDL_GPU_VERTEXELEMENTFORMAT_SHORT4_NORM
    Ushort2Norm = 27, // SDL_GPU_VERTEXELEMENTFORMAT_USHORT2_NORM
    Ushort4Norm = 28, // SDL_GPU_VERTEXELEMENTFORMAT_USHORT4_NORM
    Half2 = 29, // SDL_GPU_VERTEXELEMENTFORMAT_HALF2
    Half4 = 30, // SDL_GPU_VERTEXELEMENTFORMAT_HALF4
}
