namespace Piranha.Jawbone.Sdl3;

public enum SdlGamepadButton // SDL_GamepadButton
{
    Invalid = -1, // SDL_GAMEPAD_BUTTON_INVALID
    South = 0, // SDL_GAMEPAD_BUTTON_SOUTH
    East = 1, // SDL_GAMEPAD_BUTTON_EAST
    West = 2, // SDL_GAMEPAD_BUTTON_WEST
    North = 3, // SDL_GAMEPAD_BUTTON_NORTH
    Back = 4, // SDL_GAMEPAD_BUTTON_BACK
    Guide = 5, // SDL_GAMEPAD_BUTTON_GUIDE
    Start = 6, // SDL_GAMEPAD_BUTTON_START
    LeftStick = 7, // SDL_GAMEPAD_BUTTON_LEFT_STICK
    RightStick = 8, // SDL_GAMEPAD_BUTTON_RIGHT_STICK
    LeftShoulder = 9, // SDL_GAMEPAD_BUTTON_LEFT_SHOULDER
    RightShoulder = 10, // SDL_GAMEPAD_BUTTON_RIGHT_SHOULDER
    DpadUp = 11, // SDL_GAMEPAD_BUTTON_DPAD_UP
    DpadDown = 12, // SDL_GAMEPAD_BUTTON_DPAD_DOWN
    DpadLeft = 13, // SDL_GAMEPAD_BUTTON_DPAD_LEFT
    DpadRight = 14, // SDL_GAMEPAD_BUTTON_DPAD_RIGHT
    Misc1 = 15, // SDL_GAMEPAD_BUTTON_MISC1
    RightPaddle1 = 16, // SDL_GAMEPAD_BUTTON_RIGHT_PADDLE1
    LeftPaddle1 = 17, // SDL_GAMEPAD_BUTTON_LEFT_PADDLE1
    RightPaddle2 = 18, // SDL_GAMEPAD_BUTTON_RIGHT_PADDLE2
    LeftPaddle2 = 19, // SDL_GAMEPAD_BUTTON_LEFT_PADDLE2
    Touchpad = 20, // SDL_GAMEPAD_BUTTON_TOUCHPAD
    Misc2 = 21, // SDL_GAMEPAD_BUTTON_MISC2
    Misc3 = 22, // SDL_GAMEPAD_BUTTON_MISC3
    Misc4 = 23, // SDL_GAMEPAD_BUTTON_MISC4
    Misc5 = 24, // SDL_GAMEPAD_BUTTON_MISC5
    Misc6 = 25, // SDL_GAMEPAD_BUTTON_MISC6
    Count = 26, // SDL_GAMEPAD_BUTTON_COUNT
}
