namespace Piranha.Jawbone.Sdl3;

public enum SdlGpuBlendFactor // SDL_GPUBlendFactor
{
    Invalid = 0, // SDL_GPU_BLENDFACTOR_INVALID
    Zero = 1, // SDL_GPU_BLENDFACTOR_ZERO
    One = 2, // SDL_GPU_BLENDFACTOR_ONE
    SrcColor = 3, // SDL_GPU_BLENDFACTOR_SRC_COLOR
    OneMinusSrcColor = 4, // SDL_GPU_BLENDFACTOR_ONE_MINUS_SRC_COLOR
    DstColor = 5, // SDL_GPU_BLENDFACTOR_DST_COLOR
    OneMinusDstColor = 6, // SDL_GPU_BLENDFACTOR_ONE_MINUS_DST_COLOR
    SrcAlpha = 7, // SDL_GPU_BLENDFACTOR_SRC_ALPHA
    OneMinusSrcAlpha = 8, // SDL_GPU_BLENDFACTOR_ONE_MINUS_SRC_ALPHA
    DstAlpha = 9, // SDL_GPU_BLENDFACTOR_DST_ALPHA
    OneMinusDstAlpha = 10, // SDL_GPU_BLENDFACTOR_ONE_MINUS_DST_ALPHA
    ConstantColor = 11, // SDL_GPU_BLENDFACTOR_CONSTANT_COLOR
    OneMinusConstantColor = 12, // SDL_GPU_BLENDFACTOR_ONE_MINUS_CONSTANT_COLOR
    SrcAlphaSaturate = 13, // SDL_GPU_BLENDFACTOR_SRC_ALPHA_SATURATE
}
