namespace Piranha.Jawbone.Sdl3;

public enum SdlSystemCursor // SDL_SystemCursor
{
    Default = 0, // SDL_SYSTEM_CURSOR_DEFAULT
    Text = 1, // SDL_SYSTEM_CURSOR_TEXT
    Wait = 2, // SDL_SYSTEM_CURSOR_WAIT
    Crosshair = 3, // SDL_SYSTEM_CURSOR_CROSSHAIR
    Progress = 4, // SDL_SYSTEM_CURSOR_PROGRESS
    NwseResize = 5, // SDL_SYSTEM_CURSOR_NWSE_RESIZE
    NeswResize = 6, // SDL_SYSTEM_CURSOR_NESW_RESIZE
    EwResize = 7, // SDL_SYSTEM_CURSOR_EW_RESIZE
    NsResize = 8, // SDL_SYSTEM_CURSOR_NS_RESIZE
    Move = 9, // SDL_SYSTEM_CURSOR_MOVE
    NotAllowed = 10, // SDL_SYSTEM_CURSOR_NOT_ALLOWED
    Pointer = 11, // SDL_SYSTEM_CURSOR_POINTER
    NwResize = 12, // SDL_SYSTEM_CURSOR_NW_RESIZE
    NResize = 13, // SDL_SYSTEM_CURSOR_N_RESIZE
    NeResize = 14, // SDL_SYSTEM_CURSOR_NE_RESIZE
    EResize = 15, // SDL_SYSTEM_CURSOR_E_RESIZE
    SeResize = 16, // SDL_SYSTEM_CURSOR_SE_RESIZE
    SResize = 17, // SDL_SYSTEM_CURSOR_S_RESIZE
    SwResize = 18, // SDL_SYSTEM_CURSOR_SW_RESIZE
    WResize = 19, // SDL_SYSTEM_CURSOR_W_RESIZE
    Count = 20, // SDL_SYSTEM_CURSOR_COUNT
}
