namespace Piranha.Jawbone.Sdl3;

public enum SdlTransferCharacteristics // SDL_TransferCharacteristics
{
    Unknown = 0, // SDL_TRANSFER_CHARACTERISTICS_UNKNOWN
    Bt709 = 1, // SDL_TRANSFER_CHARACTERISTICS_BT709
    Unspecified = 2, // SDL_TRANSFER_CHARACTERISTICS_UNSPECIFIED
    Gamma22 = 4, // SDL_TRANSFER_CHARACTERISTICS_GAMMA22
    Gamma28 = 5, // SDL_TRANSFER_CHARACTERISTICS_GAMMA28
    Bt601 = 6, // SDL_TRANSFER_CHARACTERISTICS_BT601
    Smpte240 = 7, // SDL_TRANSFER_CHARACTERISTICS_SMPTE240
    Linear = 8, // SDL_TRANSFER_CHARACTERISTICS_LINEAR
    Log100 = 9, // SDL_TRANSFER_CHARACTERISTICS_LOG100
    Log100Sqrt10 = 10, // SDL_TRANSFER_CHARACTERISTICS_LOG100_SQRT10
    Iec61966 = 11, // SDL_TRANSFER_CHARACTERISTICS_IEC61966
    Bt1361 = 12, // SDL_TRANSFER_CHARACTERISTICS_BT1361
    Srgb = 13, // SDL_TRANSFER_CHARACTERISTICS_SRGB
    Bt202010Bit = 14, // SDL_TRANSFER_CHARACTERISTICS_BT2020_10BIT
    Bt202012Bit = 15, // SDL_TRANSFER_CHARACTERISTICS_BT2020_12BIT
    Pq = 16, // SDL_TRANSFER_CHARACTERISTICS_PQ
    Smpte428 = 17, // SDL_TRANSFER_CHARACTERISTICS_SMPTE428
    Hlg = 18, // SDL_TRANSFER_CHARACTERISTICS_HLG
    Custom = 31, // SDL_TRANSFER_CHARACTERISTICS_CUSTOM
}
