namespace Jawbone.Sdl2;

public enum SdlEventType : uint
{
    Unused = 0,
    Quit = 0x100,
    AppTerminating,
    AppLowMemory,
    AppWillEnterBackground,
    AppDidEnterBackground,
    AppWillEnterForeground,
    AppDidEnterForeground,
    LocaleChanged,
    DisplayEvent = 0x150,
    WindowEvent = 0x200,
    SysWmEvent,
    KeyDown = 0x300,
    KeyUp,
    TextEditing,
    TextInput,
    KeyMapChanged,
    TextEditingExt,
    MouseMotion = 0x400,
    MouseButtonDown,
    MouseButtonUp,
    MouseWheel,
    JoyAxisMotion = 0x600,
    JoyBallMotion,
    JoyHatMotion,
    JoyButtonDown,
    JoyButtonUp,
    JoyDeviceAdded,
    JoyDeviceRemoved,
    JoyBatteryUpdated,
    ControllerAxisMotion = 0x650,
    ControllerButtonDown,
    ControllerButtonUp,
    ControllerDeviceAdded,
    ControllerDeviceRemoved,
    ControllerDeviceRemapped,
    ControllerTouchpadDown,
    ControllerTouchpadMotion,
    ControllerTouchpadUp,
    ControllerTouchpadUpdate,
    FingerDown = 0x700,
    FingerUp,
    FingerMotion,
    DollarGesture = 0x800,
    DollarRecord,
    Multigesture,
    ClipboardUpdate = 0x900,
    DropFile = 0x1000,
    DropText,
    DropBegin,
    DropComplete,
    AudioDeviceAdded = 0x1100,
    AudioDeviceRemoved,
    SensorUpdate = 0x1200,
    RenderTargetsReset = 0x2000,
    RenderDeviceReset,
    PollSentinel = 0x7f00,
    UserEvent = 0x8000,
    LastEvent = 0xffff
}
