# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: .NET Merge

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    # Install the .NET workload
    - name: Install .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 9.0.x

    # Do Linting
    - name: Check Formatting
      run: dotnet format source/Piranha.Jawbone/Piranha.Jawbone.csproj --verify-no-changes

    # Execute tests
    - name: Execute unit tests
      run: dotnet test source/Piranha.Jawbone.Test/Piranha.Jawbone.Test.csproj
